### ISSUE TITLE
Cannot using ray multiprocessing pool

### ISSUE THREAD

**Issue by mj-will** [mj-will/nessai#162]
**Describe the bug**
When trying to us a multiprocessing pool from `ray` for the `pool` argument introduced in https://github.com/mj-will/nessai/pull/148 an `AttributeError` is raised:

```
Traceback (most recent call last):
  File "/home/michael/projects/nessai-dev/ray/test_ray.py", line 40, in <module>
    fs = FlowSampler(
  File "/home/michael/git_repos/nessai/nessai/flowsampler.py", line 109, in __init__
    self.ns = NestedSampler(model, output=self.output,
  File "/home/michael/git_repos/nessai/nessai/nestedsampler.py", line 174, in __init__
    self.model.configure_pool(pool=pool, n_pool=n_pool)
  File "/home/michael/git_repos/nessai/nessai/model.py", line 213, in configure_pool
    self.n_pool = self.pool._processes
AttributeError: 'Pool' object has no attribute '_processes'

```

**To Reproduce**
```python
#!/usr/bin/env python

import numpy as np
from scipy.stats import norm
from ray.util.multiprocessing import Pool

from nessai.flowsampler import FlowSampler
from nessai.model import Model
from nessai.utils import setup_logger
from nessai.utils.multiprocessing import initialise_pool_variables

output = './outdir/test_ray/'
logger = setup_logger(output=output)


class GaussianModel(Model):
    def __init__(self):
        self.names = ['x', 'y']
        self.bounds = {'x': [-10, 10], 'y': [-10, 10]}

    def log_prior(self, x):
        log_p = np.log(self.in_bounds(x))
        for n in self.names:
            log_p -= np.log(self.bounds[n][1] - self.bounds[n][0])
        return log_p

    def log_likelihood(self, x):
        log_l = np.zeros(x.size)
        for n in self.names:
            log_l += norm.logpdf(x[n])
        return log_l


model = GaussianModel()
pool = Pool(
    initializer=initialise_pool_variables,
    initargs=(model,)
)

fs = FlowSampler(
    model,
    output=output,
    resume=False,
    seed=1234,
    pool=pool,
)

fs.run()

```
**Expected behaviour**
Sampler should run and use the `ray` multiprocessing pool.

**Additional context**
* Version: `main@18fdccb3773a48a3404c11874866874634900597`
* [ray multiprocessing docs](https://docs.ray.io/en/latest/ray-more-libs/multiprocessing.html)
